# Generated by Django 5.2.14 on 2026-06-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='null', max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(default='null', max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(default='null', max_length=100, verbose_name='Apellido materno')),
                ('estado', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alergias', models.BooleanField(default=False)),
                ('alergias_detalle', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('alergico_medicamento', models.BooleanField(default=False)),
                ('alergico_medicamento_detalle', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('tipo_sangre', models.CharField(blank=True, default='null', max_length=5, null=True)),
                ('madre_nombre', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('madre_apellido_paterno', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('madre_apellido_materno', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('padre_nombre', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('padre_apellido_paterno', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('padre_apellido_materno', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('escuela', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('grado', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('promedio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('persona_recoge', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('contacto_padre', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('contacto_padre_tipo', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('contacto_alumno', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('contacto_alumno_tipo', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('curso', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('horario', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('contrato', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, default='null', null=True)),
            ],
        ),
    ]
