# Generated by Django 5.2.14 on 2026-06-02 18:59

import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alumno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/', validators=[registro.models.validar_resolucion_imagen], verbose_name='Fotografía'),
        ),
    ]
