# Generated by Django 5.2.14 on 2026-06-02 23:11

import django.core.validators
import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_alumno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contrato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='escuela',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(upload_to='alumnos/', validators=[registro.models.validar_resolucion_imagen], verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='horario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_materno',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_paterno',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_nombre',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_materno',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_paterno',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_nombre',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='persona_recoge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre'),
        ),
    ]
