# Generated by Django 5.2.14 on 2026-06-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_alumno_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alergias_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alergico_medicamento_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_materno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_paterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_materno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_paterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_nombre',
            field=models.CharField(max_length=100),
        ),
    ]
