# Generated by Django 5.2.14 on 2026-06-03 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_alumno_alergias_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor a 0.'), django.core.validators.MaxValueValidator(100, message='La edad no puede ser mayor a 100.')]),
        ),
    ]
