# Generated by Django 5.2.14 on 2026-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_alumno_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
    ]
