# Generated by Django 5.2.14 on 2026-06-03 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_alumno_madre_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(max_length=50, verbose_name='Nivel escolar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Grado'),
        ),
    ]
