# Generated by Django 5.2.14 on 2026-06-03 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_alumno_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(verbose_name='fecha de inscirpcion'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_materno',
            field=models.CharField(default='null', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_paterno',
            field=models.CharField(default='null', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_nombre',
            field=models.CharField(default='null', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_materno',
            field=models.CharField(default='null', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_paterno',
            field=models.CharField(default='null', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_nombre',
            field=models.CharField(default='null', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Promedio del ciclo anterior'),
        ),
    ]
