# Generated by Django 5.2.14 on 2026-06-03 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_alter_alumno_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Numero telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Numero telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(max_length=20, verbose_name='tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='persona_recoge',
            field=models.CharField(max_length=100, verbose_name='Persona que recoge'),
        ),
    ]
