# Generated by Django 5.2.14 on 2026-06-03 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_alumno_contacto_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='madre_correo',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='madre_telefono',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre_correo',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre_telefono',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
            preserve_default=False,
        ),
    ]
