# Generated by Django 5.2.14 on 2026-06-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_alumno_madre_correo_alumno_madre_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='', max_length=10, verbose_name='Tipo de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='', max_length=10, verbose_name='Tipo de contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
    ]
