# Generated by Django 5.2.14 on 2026-06-03 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_alumno_madre_contacto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_telefono',
            field=models.CharField(default='null', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_correo',
            field=models.EmailField(default='null', max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
