# Generated by Django 5.2.14 on 2026-06-03 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_alter_alumno_madre_contacto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_correo',
            field=models.EmailField(default='null', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_telefono',
            field=models.CharField(default='null', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_sangre',
            field=models.CharField(choices=[('', 'Seleccionar'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre'),
        ),
    ]
