# Generated by Django 5.2.14 on 2026-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_alter_alumno_contacto_alumno_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(choices=[('null', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_padre_tipo',
            field=models.CharField(choices=[('null', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(choices=[('null', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(choices=[('null', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
    ]
