# Generated by Django 5.2.14 on 2026-06-03 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_alter_alumno_contacto_alumno_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno',
            field=models.CharField(default='----------', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Numero telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_materno',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_apellido_paterno',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_correo',
            field=models.EmailField(blank=True, default='null', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_nombre',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_telefono',
            field=models.CharField(blank=True, default='----------', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_materno',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_apellido_paterno',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(blank=True, choices=[('null', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='null', max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_correo',
            field=models.EmailField(blank=True, default='null', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_nombre',
            field=models.CharField(blank=True, default='null', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_telefono',
            field=models.CharField(blank=True, default='----------', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Número telefónico'),
        ),
    ]
