# Generated by Django 5.2.14 on 2026-06-04 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_alter_alumno_contacto_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='contacto_padre',
            new_name='contacto_otro',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contacto_padre_tipo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='horario',
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_otro_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], default='Movil', max_length=10, verbose_name='Tipo de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Egresado', 'Egresado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=15),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('cupo', models.PositiveIntegerField(default=20, verbose_name='Tamaño del grupo (cupo)')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de terminación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('contrato', models.CharField(max_length=50)),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Baja', 'Baja'), ('Cancelada', 'Cancelada')], default='Activa', max_length=15)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='registro.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.grupo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alumno', 'grupo'), name='inscripcion_unica')],
            },
        ),
    ]
