# Generated by Django 5.2.14 on 2026-06-05 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_curso_rename_contacto_padre_alumno_contacto_otro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='estatus',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='año',
            field=models.PositiveIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°'), (8, '8°'), (9, '9°'), (10, '10°'), (11, '11°')], verbose_name='Año escolar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_alumno_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_otro',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Numero telefónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_otro_tipo',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato/Preparatoria', 'Bachillerato/Preparatoria'), ('TSU', 'Técnico Superior Universitario'), ('Licenciatura', 'Licenciatura'), ('Ingenieria', 'Ingeniería')], max_length=50, verbose_name='Nivel escolar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='madre_contacto_tipo',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre_contacto_tipo',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('Movil', 'Móvil'), ('Fijo', 'Fijo')], max_length=10, verbose_name='Tipo de contacto'),
        ),
    ]
