# Generated by Django 5.2.14 on 2026-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_remove_alumno_estatus_alter_alumno_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato/Preparatoria', 'Bachillerato/Preparatoria'), ('TSU', 'Técnico Superior Universitario'), ('Licenciatura', 'Licenciatura'), ('Ingenieria', 'Ingeniería')], verbose_name='Nivel escolar'),
        ),
    ]
