# Generated by Django 5.2.14 on 2026-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_alter_alumno_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato/Preparatoria', 'Bachillerato/Preparatoria'), ('Tsu', 'Técnico Superior Universitario'), ('Licenciatura', 'Licenciatura'), ('Ingenieria', 'Ingeniería')], max_length=50, verbose_name='Nivel escolar'),
        ),
    ]
