# Generated by Django 5.2.14 on 2026-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_alter_alumno_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Egresado', 'Egresado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20, verbose_name='Estatus'),
        ),
    ]
