# Generated by Django 5.2.14 on 2026-06-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_alumno_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
    ]
