# Generated by Django 5.2.14 on 2026-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_alter_alumno_estatus_alter_inscripcion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(verbose_name='Fecha de inscripción'),
        ),
    ]
