# Generated by Django 5.2.14 on 2026-06-09 23:45

import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_alter_inscripcion_fecha_baja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='contrato',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='contrato_firmado',
            field=models.BooleanField(default=False, verbose_name='Contrato firmado'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='contrato_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', validators=[registro.models.validar_pdf], verbose_name='Contrato (PDF)'),
        ),
    ]
