# Generated by Django 5.2.14 on 2026-06-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_remove_inscripcion_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_inicio',
        ),
    ]
