# Generated by Django 5.2.14 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0026_remove_grupo_fecha_fin_remove_grupo_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='año',
            field=models.PositiveIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°'), (8, '8°'), (9, '9°'), (10, '10°'), (11, '11°'), (12, '12°')], verbose_name='Año escolar'),
        ),
    ]
