# Generated by Django 5.2.14 on 2026-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_alumno_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='otro_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
