# Generated by Django 5.2.14 on 2026-06-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0028_alumno_otro_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='contrato_firmado',
        ),
    ]
